accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "Elastic-2.0",
    "LicenseRef-ring",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016"
]

# Ignore non plublished crates, such as xtask for example
private = { ignore = true }
# Ignore dependencies used in tests only, test-log for example
ignore-dev-dependencies = true

[ring.clarify]
license = "LicenseRef-ring"
[[ring.clarify.files]]
path = "LICENSE"
license = "LicenseRef-ring"
checksum = '76b39f9b371688eac9d8323f96ee80b3aef5ecbc2217f25377bd4e4a615296a9'
